@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package mods.thecomputerizer.shaderplayground.registry.dimensions;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;