@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package mods.thecomputerizer.shaderplayground.registry;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;